### ISSUE TITLE
Homepage Updates

### ISSUE THREAD

**Issue by matthall8** [FACN4/StudentProject-WeCook#122]
**Style**

- [ ] Image needs higher resolution for desktop

**Functionality**

**Priority 2:** 

- [ ] Next meal list page if search is succesfull (using the router?)

**Priority 4: Error handling for 3 scenarios** 

- [ ] 404 - Postcode does not exist
- [ ] No meals in your area
- [ ] Meals in your area but not this date
