### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by DenisKent** [FACN4/StudentProject-WeCook#6]
Parts:
- [x] Build Schema #11 
- [x] heroku db for development and testing  #13 
- [x] Write build script with dummy data #14 
- [x] Test DB build #17

**Comment by matthall8** [comment]
Fixed in above commits.
