### ISSUE TITLE
Checkout functionality

### ISSUE THREAD

**Issue by DenisKent** [FACN4/StudentProject-WeCook#86]
As a user I want to be able to see my subtotal and begin the checkout process by going to either the login page if I'm logged out or the payment page if I'm logged in.

This includes:
- [x] Create static checkout button and add it to the basket page #109
- [x] Total on the bar is updated automatically #110
- [x] Checkout function that takes user to payments page if logged in or logged in/register page if not. #111 

Notes: Should be done after payment information is setup. Links the basket page to the payment or login page.
